CONFIGS = {
    "elgiganten": {
        "vendor_desc": "Nordic technology store",
        "is_email_in_swedish": True,
        "items_desc": "electronics",
        "header_info": 'Look for "Tack for din beställning!" header.',
        "field_translations": {
            "Antal": "Amount",
            "Summa": "Sum",
            "Frakt": "Delivery fee",
            "Totalbelopp": "Total",
            "Betalningsmetod": "Payment method",
        },
    },
    "mediamarkt": {
        "vendor_desc": "European electronics store",
        "is_email_in_swedish": True,
        "items_desc": "electronics",
        "header_info": 'Look for "Ordersammanställning" header.',
        "field_translations": {
            "Ordernummer": "Order number",
            "Orderdatum": "Date of order",
            "Fakturaadress": "Billing address",
            "Leveransadress": "Delivery address",
            "Frakt": "Delivery fee",
            "Antal": "Amount",
            "Beskrivning": "Item name",
            "Styckpris": "Item price",
            "Totalsumma": "Total price",
            "Betalningsmetod": "Payment method",
        },
    },
    "proshop": {
        "vendor_desc": "online European electronics store",
        "is_email_in_swedish": True,
        "items_desc": "electronics",
        "header_info": 'Look for "Din order består av följande artiklar" header.',
        "field_translations": {
            "Kundupplysningar": "Customer information",
            "Beställningsupplysningar": "Order information",
            "Ordernummer": "Order number",
            "Betalning": "Payment method",
            "Produktnamn": "Item name",
            "Belopp": "Item price",
            "Antal": "Amount",
            "moms": "Tax",
            "Totalbelopp": "Total",
        },
    },
    "power": {
        "vendor_desc": "online Nordic consumer electronics store",
        "is_email_in_swedish": True,
        "items_desc": "electronics",
        "header_info": 'Look for "Orderinformation" header.',
        "field_translations": {
            "Beställningsdatum": "Order date (YYYY-MM-DD) and time (HH:MM)",
            "Ordernummer": "Order number",
            "Betalningssätt": "Payment method",
            "Kundinformation": "Customer information",
            "Leveransadress": "Delivery address",
            "Produkter": "Products",
            "Frakt": "Delivery information (delivery method, followed by delivery fee)",
            "Totalt": "Total",
            "moms": "tax",
        },
    },
    "cdon": {
        "vendor_desc": "online Nordic marketplace",
        "is_email_in_swedish": True,
        "items_desc": "electronics",
        "header_info": 'Look for "Tack för din beställning!" header.',
        "field_translations": {
            "Orderdatum": "Order date (YYYY-MM-DD)",
            "Orderstatus": "Order status",
            "Ordernummer": "Order number",
            "Antal varor": "Amount/Quantity",
            "Betalningsalternativ": "Payment method",
            "Fraktalternativ": "Delivery information",
            "Frakt": "Delivery fee",
            "Summa": "Total",
            "moms": "tax",
        },
    },
}
